version: '3.8'

services:
  app:
    image: openjdk:21
    working_dir: /app
    volumes:
      - ./target/demo-0.0.1-SNAPSHOT.jar:/app/app.jar
    ports:
      - "8080:8080"
    entrypoint: ["java", "-jar", "app.jar"]